[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "chatprop-web"
source = "discord-viewer"

[[services]]
name = "observant-vibrancy"
source = "discord-viewer/databento-live-test"

[[services]]
name = "discord-monitor"
source = "discord-monitor"